###########################################################################################
#########                                                                         #########
#########                     Daniel Elias Martin Herranz                         #########
#########                             06/03/2017                                  #########
#########                              EMBL-EBI                                   #########
#########                           Thornton group                                #########
#########                                                                         #########
###########################################################################################

###########################################################################################
#####                                 cuRRBS paper                                     ####
###########################################################################################
##### Create a heatmap which represents the fragment length distributions generated by ####
##### the different isochizomer families of restriction enzymes. Moreover, create a    ####
##### scatterplot of median fragment length vs total number of fragments for each family. #
###########################################################################################
##### USAGE: manual                                                                    ####
###########################################################################################


#### Dependencies ####

library(circlize);
library(ComplexHeatmap);
library(ggplot2);
library(ggrepel);
library(seqinr);
library(RColorBrewer);


#### Input arguments ####

setwd("~/Desktop/methylation_clock/optimize_RRBS/cuRRBS_paper/Figure_1/Figure_1A/");

# Fragment length distributions input file (created with obtain_distributions_and_fragments_old.py).

fld_file_path <- "fl_distributions_1_enzymes.txt";

# Size ranges to test

min_size_range <- 1;
max_size_range <- 8001; # The last size range will include all fragments with length >= max_size_range
window_length <- 200;
  

#### Functions ####

## Function: given the fragment length distribution of a restriction enzyme and the size range of
#  interest, calculate the number of fragments in the given size range. 

# fld: numeric matrix which contains the theoretical fragment length distribution. 
#      First column: fragment length. Second column: number of fragments with that size.
# size_range: range of fragment lengths selected (e.g. 40_220). If NA, then the function returns NA.


NF_calculation <- function(fld, size_range){
  
  if(is.na(size_range)){
    
    return(NA);
    
  }else{
    
    min_size_f <- as.numeric(strsplit(size_range, '_')[[1]][1]);
    max_size_f <- as.numeric(strsplit(size_range, '_')[[1]][2]);
    selected_fragments <- fld[which(fld[,1] >= min_size_f & fld[,1] <= max_size_f),];
    
    if(length(selected_fragments)>2){
      
      NF <- sum(as.numeric(selected_fragments[,2]));
      
    }
    
    if(length(selected_fragments)==2){
      
      NF <- as.numeric(selected_fragments[2]);
      
    }
    
    if(length(selected_fragments)<2){
      
      NF <- 0;
      
    }
    
    return(NF);
    
  }
}


#### Run the pipeline ####

### 1. Initialize important variables ###

print('Initializing variables ...');

## Create a vector with all the size ranges to test ##

lower_limits_vector <- seq(from=min_size_range, to=max_size_range, by=window_length);
if(lower_limits_vector[length(lower_limits_vector)] != max_size_range){
  lower_limits_vector <- c(lower_limits_vector, max_size_range);
}

upper_limits_vector <- lower_limits_vector + window_length - 1;
upper_limits_vector[length(upper_limits_vector)] <- Inf;

size_ranges_vector <- rev(paste0(lower_limits_vector, '_', upper_limits_vector)); # Order from higher to lower

## Calculate the number of enzymes in the input file and other useful variables.

fld_headers <- system(paste0("grep -n '>' ", fld_file_path), intern=T);
n_enzymes <- length(fld_headers);

fld_chunk_sep <- as.numeric(sapply(strsplit(fld_headers, ':'), function(x){x[1]})); # Line numbers
fld_enz_combs <- sub('>', '', sapply(strsplit(fld_headers, ':'), function(x){x[2]})); # Enzyme names

## Final matrix to plot. Rows: enzymes. Columns: size ranges. Values: number of fragments for a given enzyme and size range.

final_NF_matrix <- matrix(NA, nrow=n_enzymes, ncol=length(size_ranges_vector));
rownames(final_NF_matrix) <- fld_enz_combs;
colnames(final_NF_matrix) <- gsub('_', '-', size_ranges_vector);

## Median fragment length for each enzyme.

median_fragment_length <- c();


### 2. Calculate the number of fragments for each one of the size ranges and each one of the enzymes ###

print('Calculating final matrix ...');

fld_file <- file(fld_file_path);
open(fld_file);

for(i in 1:length(fld_chunk_sep)){
  
  # Read the fld chunk for the current enzyme
  
  if(i == length(fld_chunk_sep)){ # For the last enzyme
    
    current_fld <- readLines(fld_file, n=-1);

  }else{
    
    current_fld <- readLines(fld_file, n=fld_chunk_sep[i+1] - fld_chunk_sep[i]); 

  }
  
  # Format the fld chunk of information.
  
  current_fld <- current_fld[-1];
  current_fld <- matrix(as.numeric(unlist(strsplit(current_fld, ','))), ncol=2, byrow=T);
  
  # Calcualte the number of fragments for each size range.

  final_NF_matrix[i,] <- sapply(size_ranges_vector, NF_calculation, fld=current_fld);
  
  # Calculate the median fragment length for the current enzyme.
  
  median_fragment_length <- c(median_fragment_length, median(rep(current_fld[,1], current_fld[,2])));
  
}

close(fld_file);


### 4. Generate a heatmap for the final matrix. Rows: size ranges. Columns: enzymes. Intensity: proportion of fragments (from the total) in the given size range and enzyme 

print('Creating heatmap ...');

## Transform the matrix from absolute numbers to proportions of the total number of fragments per enzyme.

total_NF <- rowSums(final_NF_matrix);
proportions_matrix <- final_NF_matrix/total_NF;
proportions_matrix <- log(proportions_matrix,base = 10);

## Convert the -Inf values to NAs

proportions_matrix[which(proportions_matrix == "-Inf")] <- NA;

## Transpose the matrix to show the results in a gel-like way. i.e. rows: size ranges, columns: enzymes

pmt <- t(proportions_matrix);

## Obtain the GC content for the motifs of the different enzymes

motifs <- read.table("recognition_sites_enzymes.csv", header = F, sep = ",");

if(!all(as.character(motifs[,1]) == colnames(pmt))){
  stop("Please, order the isoschizomer names correctly");
}

motifs_seqs <- strsplit(as.character(motifs[,2]),"");
numberAT <- sapply(motifs_seqs, GC, exact=TRUE);
numberAT[which(numberAT>=0 & numberAT<0.25)] <- '0-25';
numberAT[which(numberAT>=0.25 & numberAT<0.5)] <- '25-50';
numberAT[which(numberAT>=0.5 & numberAT<0.75)] <- '50-75';
numberAT[which(numberAT>=0.75 & numberAT<=1)] <- '75-100';

## Heatmap annotation (total NF, median fragment length, GC content)

log_total_NF <- log(total_NF);
lnt_col <- colorRamp2(c(floor(min(log_total_NF)), ceiling(max(log_total_NF))), c("white", "red"));
log_median_l <- log(median_fragment_length);
lmedian_col <- colorRamp2(c(floor(min(log_median_l)), ceiling(max(log_median_l))), c("white", "skyblue3"));
gc_col <- c("0-25"=brewer.pal(n=5, name = "YlGn")[2],
            "25-50"=brewer.pal(n=5, name = "YlGn")[3],
            "50-75"=brewer.pal(n=5, name = "YlGn")[4],
            "75-100"=brewer.pal(n=5, name = "YlGn")[5]);

annotation_df <- data.frame(log_total_NF=log_total_NF, log_median_length = log_median_l, gc_content = numberAT);
ha <- HeatmapAnnotation(df = annotation_df,
                        col = list(log_total_NF = lnt_col, log_median_length = lmedian_col, gc_content = gc_col),
                        annotation_legend_param=list(log_total_NF = list(title='Total number\n of fragments',
                                                                         at=c(log(10^4), log(10^5), log(10^6), log(10^7), log(10^8)),
                                                                         labels=c(expression(10^4), expression(10^5), expression(10^6), expression(10^7), expression(10^8))),
                                                     log_median_length = list(title='Median fragment\n length (in bp)',
                                                                            at=c(log(10^2), log(10^3), log(10^4), log(10^5)),
                                                                            labels=c(expression(10^2),expression(10^3),expression(10^4),expression(10^5))),
                                                     gc_content = list(title='GC content (%)', 
                                                                       labels=c('0-25', '25-50', '50-75', '75-100'))));

## Plot the transposed matrix with the proportions in the heatmap. 
# Include annotation with total number of fragments per enzyme and median fragment length

col_scale <- colorRamp2(c(min(pmt, na.rm = T), max(pmt, na.rm = T)),c("darkblue","yellow2"));

pdf('theoretical_fld_heatmap.pdf', width=14, height=8);

Heatmap(pmt, cluster_rows=FALSE, col=col_scale, column_dend_side = "top",
        heatmap_legend_param = list(title = "Proportion\nof fragments", title_position='topcenter',at=c(0,-1,-2,-4,-8), 
                                    labels=c(expression(10^0),expression(10^-1),expression(10^-2),expression(10^-4), expression(10^-8))),
        column_title="Restriction enzymes (isoschizomer families)", column_title_gp = gpar(fontsize = 15, fontface = "bold"), column_title_side = "top",
        column_names_side = "top", column_names_gp = gpar(fontsize = 4.5),
        row_title="Size ranges (in bp)", row_title_gp = gpar(fontsize = 15, fontface = "bold"),
        row_names_gp = gpar(fontsize = 8),
        top_annotation =ha);

dev.off();


### 5. Generate a scatterplot of median fragment length vs total number of fragments. ###

print('Creating scatterplot ...');

scatter_data <- data.frame(enzymes=names(total_NF), total_number=as.numeric(total_NF), median_length=as.numeric(median_fragment_length));

scatter_plot <- ggplot(scatter_data, aes(x=median_length, y=total_number)) + 
  geom_point(size=0.7, col='red') + geom_text_repel(aes(label=enzymes), segment.alpha=0.3, force=2) + 
  theme_classic() + 
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=14,face="bold")) +
  xlab('Median fragment length (in bp)') + ylab('Total number of fragments') + 
  scale_x_continuous(trans='log', breaks=c(100,1000,10000,100000), labels=c(expression(10^2),expression(10^3),expression(10^4),expression(10^5))) + 
  scale_y_continuous(trans='log', breaks=c(10000,100000,1000000,10000000,100000000), labels=c(expression(10^4), expression(10^5), expression(10^6), expression(10^7), expression(10^8)));

ggsave(filename='median_fl_vs_NF.pdf', plot=scatter_plot, width=10, height=10);
  
#### End of the script ####
